/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;



import javax.swing.table.DefaultTableModel;
import models.Adresse;
import models.Medecin;

/**
 * 
 * @author TOSHIBA
 *
 */
public class formulaireMedecin extends javax.swing.JDialog {

    public formulaireMedecin() {
        //pour afficher les bouttons autrement ça sera vide
        initComponents();
        
    }
    
    

    /**
     * Creates new form formulaireMedecin
     * @param parent
     * @param modal
     */
    public formulaireMedecin(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameMedecin = new javax.swing.JLabel();
        nameMed = new javax.swing.JTextField();
        firstNameMedecin = new javax.swing.JLabel();
        firstNameMed = new javax.swing.JTextField();
        adresseMedecin = new javax.swing.JLabel();
        wilayaMed = new javax.swing.JTextField();
        dayraMed = new javax.swing.JTextField();
        mailMedecin = new javax.swing.JLabel();
        mailMed = new javax.swing.JTextField();
        phoneMedecin = new javax.swing.JLabel();
        phoneMed = new javax.swing.JTextField();
        dateIntegrationMedecin = new javax.swing.JLabel();
        dateIntegrationMed = new javax.swing.JTextField();
        bCancelMedecin = new javax.swing.JButton();
        bSaveMedecin = new javax.swing.JButton();
        idMedecin = new javax.swing.JLabel();
        idMed = new javax.swing.JTextField();
        dayraMedecin = new javax.swing.JLabel();
        wilayaMedecin = new javax.swing.JLabel();
        arrierePlan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouveau Medecin");
        setBounds(new java.awt.Rectangle(0, 0, 600, 500));
        setMinimumSize(new java.awt.Dimension(700, 530));
        setModal(true);
        getContentPane().setLayout(null);

        nameMedecin.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        nameMedecin.setForeground(new java.awt.Color(204, 191, 160));
        nameMedecin.setText("Nom");
        getContentPane().add(nameMedecin);
        nameMedecin.setBounds(20, 140, 65, 23);

        nameMed.setBackground(new java.awt.Color(204, 204, 255));
        nameMed.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nameMed.setText(" ");
        nameMed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.blue, null, null));
        nameMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameMedActionPerformed(evt);
            }
        });
        getContentPane().add(nameMed);
        nameMed.setBounds(150, 140, 185, 19);

        firstNameMedecin.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        firstNameMedecin.setForeground(new java.awt.Color(204, 191, 160));
        firstNameMedecin.setText("Prenom");
        getContentPane().add(firstNameMedecin);
        firstNameMedecin.setBounds(20, 170, 65, 23);

        firstNameMed.setBackground(new java.awt.Color(204, 204, 255));
        firstNameMed.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        firstNameMed.setText(" ");
        firstNameMed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.blue, null, null));
        firstNameMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameMedActionPerformed(evt);
            }
        });
        getContentPane().add(firstNameMed);
        firstNameMed.setBounds(150, 170, 185, 19);

        adresseMedecin.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        adresseMedecin.setForeground(new java.awt.Color(204, 191, 160));
        adresseMedecin.setText("Adresse");
        getContentPane().add(adresseMedecin);
        adresseMedecin.setBounds(20, 200, 65, 23);

        wilayaMed.setBackground(new java.awt.Color(204, 204, 255));
        wilayaMed.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        wilayaMed.setText(" ");
        wilayaMed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.blue, null, null));
        getContentPane().add(wilayaMed);
        wilayaMed.setBounds(250, 240, 140, 20);

        dayraMed.setBackground(new java.awt.Color(204, 204, 255));
        dayraMed.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dayraMed.setText(" ");
        dayraMed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.blue, null, null));
        getContentPane().add(dayraMed);
        dayraMed.setBounds(80, 240, 140, 20);

        mailMedecin.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        mailMedecin.setForeground(new java.awt.Color(204, 191, 160));
        mailMedecin.setText("e-mail");
        getContentPane().add(mailMedecin);
        mailMedecin.setBounds(20, 300, 65, 23);

        mailMed.setBackground(new java.awt.Color(204, 204, 255));
        mailMed.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mailMed.setText(" ");
        mailMed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.blue, null, null));
        getContentPane().add(mailMed);
        mailMed.setBounds(150, 300, 185, 19);

        phoneMedecin.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        phoneMedecin.setForeground(new java.awt.Color(204, 191, 160));
        phoneMedecin.setText("Telephone");
        getContentPane().add(phoneMedecin);
        phoneMedecin.setBounds(20, 330, 76, 23);

        phoneMed.setBackground(new java.awt.Color(204, 204, 255));
        phoneMed.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        phoneMed.setText(" ");
        phoneMed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.blue, null, null));
        getContentPane().add(phoneMed);
        phoneMed.setBounds(150, 330, 185, 19);

        dateIntegrationMedecin.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        dateIntegrationMedecin.setForeground(new java.awt.Color(204, 191, 160));
        dateIntegrationMedecin.setText("Date Intergation");
        getContentPane().add(dateIntegrationMedecin);
        dateIntegrationMedecin.setBounds(20, 360, 105, 23);

        dateIntegrationMed.setBackground(new java.awt.Color(204, 204, 255));
        dateIntegrationMed.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dateIntegrationMed.setText(" ");
        dateIntegrationMed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.blue, null, null));
        getContentPane().add(dateIntegrationMed);
        dateIntegrationMed.setBounds(150, 360, 185, 19);

        bCancelMedecin.setText("Annuler");
        bCancelMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelMedecinActionPerformed(evt);
            }
        });
        getContentPane().add(bCancelMedecin);
        bCancelMedecin.setBounds(340, 400, 100, 23);

        bSaveMedecin.setText("Enregister");
        bSaveMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveMedecinActionPerformed(evt);
            }
        });
        getContentPane().add(bSaveMedecin);
        bSaveMedecin.setBounds(210, 400, 100, 23);

        idMedecin.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        idMedecin.setForeground(new java.awt.Color(204, 191, 160));
        idMedecin.setText("ID");
        getContentPane().add(idMedecin);
        idMedecin.setBounds(30, 110, 65, 23);

        idMed.setBackground(new java.awt.Color(204, 204, 255));
        idMed.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        idMed.setText(" ");
        idMed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.blue, null, null));
        idMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMedActionPerformed(evt);
            }
        });
        getContentPane().add(idMed);
        idMed.setBounds(150, 110, 185, 19);

        dayraMedecin.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        dayraMedecin.setForeground(new java.awt.Color(204, 191, 160));
        dayraMedecin.setText("Dayra");
        getContentPane().add(dayraMedecin);
        dayraMedecin.setBounds(120, 210, 60, 23);

        wilayaMedecin.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        wilayaMedecin.setForeground(new java.awt.Color(204, 191, 160));
        wilayaMedecin.setText("Wilaya");
        getContentPane().add(wilayaMedecin);
        wilayaMedecin.setBounds(280, 210, 60, 23);

        arrierePlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/img/mainWindowBackground.png"))); // NOI18N
        getContentPane().add(arrierePlan);
        arrierePlan.setBounds(0, 0, 720, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelMedecinActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
    }//GEN-LAST:event_bCancelMedecinActionPerformed

    private void bSaveMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveMedecinActionPerformed
         //la requette de base de donnée   
       /* Medecin med= formulaireMedecin.ajouterMedecin();
        /* new  formulaireMedecin().setVisible(true);*/
      /*DefaultTableModel model1;
       model1= (DefaultTableModel)new ListeMedecins().getListeMedecin().getModel();
       model1.addRow(
       new Object[]  {
           med.getId(),
           med.getName(),
           med.getFirstName(),
           med.getAdresse(),
           med.getMail(),
           med.getPhoneNumber(),
           med.getDateIntegration()
       });*/
      /* new ListeMedecins().setVisible(true);*/
             this.setVisible(false);
       
    }//GEN-LAST:event_bSaveMedecinActionPerformed

    private void nameMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameMedActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameMedActionPerformed

    private void idMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMedActionPerformed

    private void firstNameMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameMedActionPerformed
    
    //création 
    public Medecin getMedecin (){
        
        int identifiant = Integer.parseInt(idMed.getText().trim());
        Adresse adrMed=new Adresse(dayraMed.getText(),wilayaMed.getText());
       
        
        Medecin med;
        med = new Medecin(
                identifiant,
                nameMed.getText(),
                firstNameMed.getText(),
                mailMed.getText(),
                phoneMed.getText(),
                adrMed,
                dateIntegrationMed.getText()
        );
        
        
      
        return med;
    }
    
    // creation d'un nouveau formulaire
    public static Medecin ajouterMedecin(){
        formulaireMedecin formulaireMed=new formulaireMedecin();
        formulaireMed.setVisible(true);
        Medecin med;
        med = formulaireMed.getMedecin();
        
        return med;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulaireMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulaireMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulaireMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulaireMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                formulaireMedecin dialog = new formulaireMedecin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.pack();
                dialog.setVisible(true);
                
                
            }
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresseMedecin;
    private javax.swing.JLabel arrierePlan;
    private javax.swing.JButton bCancelMedecin;
    private javax.swing.JButton bSaveMedecin;
    private javax.swing.JTextField dateIntegrationMed;
    private javax.swing.JLabel dateIntegrationMedecin;
    private javax.swing.JTextField dayraMed;
    private javax.swing.JLabel dayraMedecin;
    private javax.swing.JTextField firstNameMed;
    private javax.swing.JLabel firstNameMedecin;
    private javax.swing.JTextField idMed;
    private javax.swing.JLabel idMedecin;
    private javax.swing.JTextField mailMed;
    private javax.swing.JLabel mailMedecin;
    private javax.swing.JTextField nameMed;
    private javax.swing.JLabel nameMedecin;
    private javax.swing.JTextField phoneMed;
    private javax.swing.JLabel phoneMedecin;
    private javax.swing.JTextField wilayaMed;
    private javax.swing.JLabel wilayaMedecin;
    // End of variables declaration//GEN-END:variables
}
